name: Windows

on:
  push:
    branches: [ master, github, explore ]
    paths-ignore:
      - 'README.rst'
      - 'doc/**'
  pull_request:
    branches: [ master, github, explore ]
    paths-ignore:
      - 'README.rst'
      - 'doc/**'

jobs:
  vs2022:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: cmake -E make_directory build

    - shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 17 2022"

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
